

Deployment:
      ###########################
      ## the total number of orderer
      ###########################
      orderer: 3
      ###########################
      ## the total number of organization
      ###########################
      organization: 3
      ###########################
      ## the number of peer of each organization
      ###########################
      peer: 2
      ###########################
      ## the number of server/instance
      ###########################      
      server: 3
      ###########################
      ## configuration of blockchain node
      ## orderer, orderer2, orderer3, orderer4 ...
      ## peer0.org1, peer1.org1, peer0.org2, peer1.org2 ...
      ###########################  
      deployment:
          - Host: 1
            configuration:
              - 'peer0.org1'
              - 'peer1.org1'
              - 'orderer'
          - Host: 2
            configuration:
              - 'peer0.org2'
              - 'peer1.org2'
              - 'orderer2'
          - Host: 3
            configuration:
              - 'peer0.org3'
              - 'peer1.org3'
              - 'orderer3'
      ###########################
      ## type of chaincode 
      ###########################  
      chaincode: 'fabcar'


