version: '3.7'
volumes:
  peer1.org2.example.com: {}
networks:
  test:
    name: testnet
    external: 'true'
services:
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_ADDRESS=peer1.org2.example.com:8201
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8201
    - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:20201
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20201
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:8200
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:8201
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org2.example.com:40201
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
    - peer1.org2.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8201:8201
    - 20201:20201
    - 40201:40201
    networks:
    - test
