version: '3.7'
volumes:
  peer1.org3.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:
  peer0.org3.example.com:
  peer0.org2.example.com:
  peer1.org2.example.com:
  cli:
  orderer.example.com:
  orderer2.example.com:
  orderer3.example.com:
networks:
  test:
    name: testnet
    external: 'true'
services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.5
    tty: true
    stdin_open: true
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - FABRIC_LOGGING_SPEC=INFO
    - SYS_CHANNEL=system-channel
    - CORE_PEER_ID=cli
    - CORE_PEER_ADDRESS=peer0.org1.example.com:8100
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
    - /var/run/:/host/var/run/
    - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
    - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    - ../caliper-benchmarks:/opt/gopath/src/github.com/hyperledger/fabric/peer/caliper-benchmarks
    command: /bin/bash
    networks:
    - test

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.2.5
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7050
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:30000
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    - ../configtx/:/var/hyperledger/config
    command: orderer
    ports:
    - 7050:7050
    - 30000:30000
    networks:
    - test
  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer:2.2.5
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7051
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:30001
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer2.example.com:/var/hyperledger/production/orderer
    - ../configtx/:/var/hyperledger/config
    command: orderer
    ports:
    - 7051:7051
    - 30001:30001
    networks:
    - test
  orderer3.example.com:
    container_name: orderer3.example.com
    image: hyperledger/fabric-orderer:2.2.5
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7052
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:30002
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer3.example.com:/var/hyperledger/production/orderer
    - ../configtx/:/var/hyperledger/config
    command: orderer
    ports:
    - 7052:7052
    - 30002:30002
    networks:
    - test
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org1.example.com
    - CORE_PEER_ADDRESS=peer0.org1.example.com:8100
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8100
    - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:20100
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20100
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:8101
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8100
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:40100
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
    - peer0.org1.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8100:8100
    - 20100:20100
    - 40100:40100
    networks:
    - test
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org2.example.com
    - CORE_PEER_ADDRESS=peer0.org2.example.com:8200
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8200
    - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:20200
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20200
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:8201
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:8200
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.example.com:40200
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
    - peer0.org2.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8200:8200
    - 20200:20200
    - 40200:40200
    networks:
    - test
  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.org3.example.com
    - CORE_PEER_ADDRESS=peer0.org3.example.com:8300
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8300
    - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:20300
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20300
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:8301
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:8300
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.example.com:40300
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
    - peer0.org3.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8300:8300
    - 20300:20300
    - 40300:40300
    networks:
    - test
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_ADDRESS=peer1.org1.example.com:8101
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8101
    - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:20101
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20101
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8100
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8101
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:40101
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
    - peer1.org1.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8101:8101
    - 20101:20101
    - 40101:40101
    networks:
    - test

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_ADDRESS=peer1.org2.example.com:8201
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8201
    - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:20201
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20201
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:8200
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:8201
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org2.example.com:40201
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
    - peer1.org2.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8201:8201
    - 20201:20201
    - 40201:40201
    networks:
    - test
  peer1.org3.example.com:
    container_name: peer1.org3.example.com
    image: hyperledger/fabric-peer:2.2.5
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=testnet
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer1.org3.example.com
    - CORE_PEER_ADDRESS=peer1.org3.example.com:8301
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8301
    - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:20301
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:20301
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.example.com:8301
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:8300
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_OPERATIONS_LISTENADDRESS=peer1.org3.example.com:40301
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - /var/run/docker.sock:/host/var/run/docker.sock
    - ../organizations/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/tls
    - peer1.org3.example.com:/var/hyperledger/production
    - ../configtx/:/var/hyperledger/config
    command: peer node start
    ports:
    - 8301:8301
    - 20301:20301
    - 40301:40301
    networks:
    - test
